"""Added latitude and longitude attributes to our Garden model

Revision ID: 2cc2e96ffdbd
Revises: 
Create Date: 2025-03-14 11:32:28.486911

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2cc2e96ffdbd'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('hours_of_operation')
    with op.batch_alter_table('garden', schema=None) as batch_op:
        batch_op.add_column(sa.Column('latitude', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('longitude', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('garden', schema=None) as batch_op:
        batch_op.drop_column('longitude')
        batch_op.drop_column('latitude')

    op.create_table('hours_of_operation',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('day', sa.VARCHAR(length=10), nullable=False),
    sa.Column('opening_time', sa.TIME(), nullable=False),
    sa.Column('closing_time', sa.TIME(), nullable=False),
    sa.Column('garden_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['garden_id'], ['garden.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
